# Generated by Django 3.2.8 on 2023-02-13 13:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
