# Generated by Django 4.1.6 on 2023-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_ad_date_ad_description_ad_price_ad_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
