# Generated by Django 4.1.6 on 2023-02-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_ad_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='type',
            field=models.BooleanField(default='False'),
        ),
    ]
