# Generated by Django 4.1.6 on 2023-02-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ad_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='type',
            new_name='isRequest',
        ),
    ]
